spring.application.name=gymflow
#Coneccion mysql
spring.datasource.url=jdbc:mysql://localhost:3306/gymflow_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#LOGS
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
logging.level.root=INFO
#banner
spring.main.banner-mode=off
